// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group_message.proto

package edu.uiuc.groupmessage;

public final class GroupMessageProtos {
	private GroupMessageProtos() {}
	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}
	public interface MemberOrBuilder
	extends com.google.protobuf.MessageOrBuilder {

		// required string ip = 1;
		boolean hasIp();
		String getIp();

		// required int32 port = 2;
		boolean hasPort();
		int getPort();

		// optional int32 timestamp = 3;
		boolean hasTimestamp();
		int getTimestamp();
	}
	public static final class Member extends
	com.google.protobuf.GeneratedMessage
	implements MemberOrBuilder {
		// Use Member.newBuilder() to construct.
		private Member(Builder builder) {
			super(builder);
		}
		private Member(boolean noInit) {}

		private static final Member defaultInstance;
		public static Member getDefaultInstance() {
			return defaultInstance;
		}

		public Member getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return edu.uiuc.groupmessage.GroupMessageProtos.internal_static_Member_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
		internalGetFieldAccessorTable() {
			return edu.uiuc.groupmessage.GroupMessageProtos.internal_static_Member_fieldAccessorTable;
		}

		private int bitField0_;
		// required string ip = 1;
		public static final int IP_FIELD_NUMBER = 1;
		private java.lang.Object ip_;
		public boolean hasIp() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}
		public String getIp() {
			java.lang.Object ref = ip_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					ip_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getIpBytes() {
			java.lang.Object ref = ip_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				ip_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required int32 port = 2;
		public static final int PORT_FIELD_NUMBER = 2;
		private int port_;
		public boolean hasPort() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}
		public int getPort() {
			return port_;
		}

		// optional int32 timestamp = 3;
		public static final int TIMESTAMP_FIELD_NUMBER = 3;
		private int timestamp_;
		public boolean hasTimestamp() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}
		public int getTimestamp() {
			return timestamp_;
		}

		private void initFields() {
			ip_ = "";
			port_ = 0;
			timestamp_ = 0;
		}
		private byte memoizedIsInitialized = -1;
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) return isInitialized == 1;

			if (!hasIp()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasPort()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getIpBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt32(2, port_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeInt32(3, timestamp_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(1, getIpBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream
						.computeInt32Size(2, port_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream
						.computeInt32Size(3, timestamp_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;
		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static edu.uiuc.groupmessage.GroupMessageProtos.Member parseFrom(
				com.google.protobuf.ByteString data)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.Member parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.Member parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.Member parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.Member parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.Member parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.Member parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.Member parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.Member parseFrom(
				com.google.protobuf.CodedInputStream input)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.Member parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() { return Builder.create(); }
		public Builder newBuilderForType() { return newBuilder(); }
		public static Builder newBuilder(edu.uiuc.groupmessage.GroupMessageProtos.Member prototype) {
			return newBuilder().mergeFrom(prototype);
		}
		public Builder toBuilder() { return newBuilder(this); }

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}
		public static final class Builder extends
		com.google.protobuf.GeneratedMessage.Builder<Builder>
		implements edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return edu.uiuc.groupmessage.GroupMessageProtos.internal_static_Member_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
			internalGetFieldAccessorTable() {
				return edu.uiuc.groupmessage.GroupMessageProtos.internal_static_Member_fieldAccessorTable;
			}

			// Construct using edu.uiuc.groupmessage.GroupMessageProtos.Member.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}
			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}
			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				ip_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				port_ = 0;
				bitField0_ = (bitField0_ & ~0x00000002);
				timestamp_ = 0;
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return edu.uiuc.groupmessage.GroupMessageProtos.Member.getDescriptor();
			}

			public edu.uiuc.groupmessage.GroupMessageProtos.Member getDefaultInstanceForType() {
				return edu.uiuc.groupmessage.GroupMessageProtos.Member.getDefaultInstance();
			}

			public edu.uiuc.groupmessage.GroupMessageProtos.Member build() {
				edu.uiuc.groupmessage.GroupMessageProtos.Member result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private edu.uiuc.groupmessage.GroupMessageProtos.Member buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				edu.uiuc.groupmessage.GroupMessageProtos.Member result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(
							result).asInvalidProtocolBufferException();
				}
				return result;
			}

			public edu.uiuc.groupmessage.GroupMessageProtos.Member buildPartial() {
				edu.uiuc.groupmessage.GroupMessageProtos.Member result = new edu.uiuc.groupmessage.GroupMessageProtos.Member(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.ip_ = ip_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.port_ = port_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.timestamp_ = timestamp_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof edu.uiuc.groupmessage.GroupMessageProtos.Member) {
					return mergeFrom((edu.uiuc.groupmessage.GroupMessageProtos.Member)other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(edu.uiuc.groupmessage.GroupMessageProtos.Member other) {
				if (other == edu.uiuc.groupmessage.GroupMessageProtos.Member.getDefaultInstance()) return this;
				if (other.hasIp()) {
					setIp(other.getIp());
				}
				if (other.hasPort()) {
					setPort(other.getPort());
				}
				if (other.hasTimestamp()) {
					setTimestamp(other.getTimestamp());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasIp()) {

					return false;
				}
				if (!hasPort()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields =
						com.google.protobuf.UnknownFieldSet.newBuilder(
								this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						ip_ = input.readBytes();
						break;
					}
					case 16: {
						bitField0_ |= 0x00000002;
						port_ = input.readInt32();
						break;
					}
					case 24: {
						bitField0_ |= 0x00000004;
						timestamp_ = input.readInt32();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required string ip = 1;
			private java.lang.Object ip_ = "";
			public boolean hasIp() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}
			public String getIp() {
				java.lang.Object ref = ip_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					ip_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setIp(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				ip_ = value;
				onChanged();
				return this;
			}
			public Builder clearIp() {
				bitField0_ = (bitField0_ & ~0x00000001);
				ip_ = getDefaultInstance().getIp();
				onChanged();
				return this;
			}
			void setIp(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				ip_ = value;
				onChanged();
			}

			// required int32 port = 2;
			private int port_ ;
			public boolean hasPort() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}
			public int getPort() {
				return port_;
			}
			public Builder setPort(int value) {
				bitField0_ |= 0x00000002;
				port_ = value;
				onChanged();
				return this;
			}
			public Builder clearPort() {
				bitField0_ = (bitField0_ & ~0x00000002);
				port_ = 0;
				onChanged();
				return this;
			}

			// optional int32 timestamp = 3;
			private int timestamp_ ;
			public boolean hasTimestamp() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}
			public int getTimestamp() {
				return timestamp_;
			}
			public Builder setTimestamp(int value) {
				bitField0_ |= 0x00000004;
				timestamp_ = value;
				onChanged();
				return this;
			}
			public Builder clearTimestamp() {
				bitField0_ = (bitField0_ & ~0x00000004);
				timestamp_ = 0;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:Member)
		}

		static {
			defaultInstance = new Member(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:Member)
	}

	public interface GroupMessageOrBuilder
	extends com.google.protobuf.MessageOrBuilder {

		// required .Member target = 1;
		boolean hasTarget();
		edu.uiuc.groupmessage.GroupMessageProtos.Member getTarget();
		edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder getTargetOrBuilder();

		// required .GroupMessage.Action action = 2 [default = TARGET_HEARTBEATS];
		boolean hasAction();
		edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.Action getAction();

		// repeated .Member member = 3;
		java.util.List<edu.uiuc.groupmessage.GroupMessageProtos.Member> 
		getMemberList();
		edu.uiuc.groupmessage.GroupMessageProtos.Member getMember(int index);
		int getMemberCount();
		java.util.List<? extends edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder> 
		getMemberOrBuilderList();
		edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder getMemberOrBuilder(
				int index);

		// optional bytes file_content = 4;
		boolean hasFileContent();
		com.google.protobuf.ByteString getFileContent();

		// optional string file_name = 5;
		boolean hasFileName();
		String getFileName();
	}
	public static final class GroupMessage extends
	com.google.protobuf.GeneratedMessage
	implements GroupMessageOrBuilder {
		// Use GroupMessage.newBuilder() to construct.
		private GroupMessage(Builder builder) {
			super(builder);
		}
		private GroupMessage(boolean noInit) {}

		private static final GroupMessage defaultInstance;
		public static GroupMessage getDefaultInstance() {
			return defaultInstance;
		}

		public GroupMessage getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return edu.uiuc.groupmessage.GroupMessageProtos.internal_static_GroupMessage_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
		internalGetFieldAccessorTable() {
			return edu.uiuc.groupmessage.GroupMessageProtos.internal_static_GroupMessage_fieldAccessorTable;
		}

		public enum Action
		implements com.google.protobuf.ProtocolMessageEnum {
			JOIN_REQUEST(0, 0),
			RESET_MEMBERLIST(1, 1),
			TARGET_JOINS(2, 2),
			TARGET_LEAVES(3, 3),
			TARGET_FAILS(4, 4),
			TARGET_HEARTBEATS(5, 5),
			GET_FILE_LOCATION(6, 6),
			FILE_LOCATION(7, 7),
			PUT_FILE(8, 8),
			GET_FILE(9, 9),
			DELETE_FILE(10, 10),
			DELETE_REPLICA(11, 11),
			FILE_OK(12, 12),
			FILE_ERROR(13, 13),
			PUSH_FILE(14, 14),
			FILE_NOT_EXIST(15, 15),
			FILE_EXIST(16, 16),
			CHECK_FILE_EXIST(17, 17),
			;

			public static final int JOIN_REQUEST_VALUE = 0;
			public static final int RESET_MEMBERLIST_VALUE = 1;
			public static final int TARGET_JOINS_VALUE = 2;
			public static final int TARGET_LEAVES_VALUE = 3;
			public static final int TARGET_FAILS_VALUE = 4;
			public static final int TARGET_HEARTBEATS_VALUE = 5;
			public static final int GET_FILE_LOCATION_VALUE = 6;
			public static final int FILE_LOCATION_VALUE = 7;
			public static final int PUT_FILE_VALUE = 8;
			public static final int GET_FILE_VALUE = 9;
			public static final int DELETE_FILE_VALUE = 10;
			public static final int DELETE_REPLICA_VALUE = 11;
			public static final int FILE_OK_VALUE = 12;
			public static final int FILE_ERROR_VALUE = 13;
			public static final int PUSH_FILE_VALUE = 14;
			public static final int FILE_NOT_EXIST_VALUE = 15;
			public static final int FILE_EXIST_VALUE = 16;
			public static final int CHECK_FILE_EXIST_VALUE = 17;


			public final int getNumber() { return value; }

			public static Action valueOf(int value) {
				switch (value) {
				case 0: return JOIN_REQUEST;
				case 1: return RESET_MEMBERLIST;
				case 2: return TARGET_JOINS;
				case 3: return TARGET_LEAVES;
				case 4: return TARGET_FAILS;
				case 5: return TARGET_HEARTBEATS;
				case 6: return GET_FILE_LOCATION;
				case 7: return FILE_LOCATION;
				case 8: return PUT_FILE;
				case 9: return GET_FILE;
				case 10: return DELETE_FILE;
				case 11: return DELETE_REPLICA;
				case 12: return FILE_OK;
				case 13: return FILE_ERROR;
				case 14: return PUSH_FILE;
				case 15: return FILE_NOT_EXIST;
				case 16: return FILE_EXIST;
				case 17: return CHECK_FILE_EXIST;
				default: return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<Action>
			internalGetValueMap() {
				return internalValueMap;
			}
			private static com.google.protobuf.Internal.EnumLiteMap<Action>
			internalValueMap =
			new com.google.protobuf.Internal.EnumLiteMap<Action>() {
				public Action findValueByNumber(int number) {
					return Action.valueOf(number);
				}
			};

			public final com.google.protobuf.Descriptors.EnumValueDescriptor
			getValueDescriptor() {
				return getDescriptor().getValues().get(index);
			}
			public final com.google.protobuf.Descriptors.EnumDescriptor
			getDescriptorForType() {
				return getDescriptor();
			}
			public static final com.google.protobuf.Descriptors.EnumDescriptor
			getDescriptor() {
				return edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.getDescriptor().getEnumTypes().get(0);
			}

			private static final Action[] VALUES = {
				JOIN_REQUEST, RESET_MEMBERLIST, TARGET_JOINS, TARGET_LEAVES, TARGET_FAILS, TARGET_HEARTBEATS, GET_FILE_LOCATION, FILE_LOCATION, PUT_FILE, GET_FILE, DELETE_FILE, DELETE_REPLICA, FILE_OK, FILE_ERROR, PUSH_FILE, FILE_NOT_EXIST, FILE_EXIST, CHECK_FILE_EXIST, 
			};

			public static Action valueOf(
					com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new java.lang.IllegalArgumentException(
							"EnumValueDescriptor is not for this type.");
				}
				return VALUES[desc.getIndex()];
			}

			private final int index;
			private final int value;

			private Action(int index, int value) {
				this.index = index;
				this.value = value;
			}

			// @@protoc_insertion_point(enum_scope:GroupMessage.Action)
		}

		private int bitField0_;
		// required .Member target = 1;
		public static final int TARGET_FIELD_NUMBER = 1;
		private edu.uiuc.groupmessage.GroupMessageProtos.Member target_;
		public boolean hasTarget() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}
		public edu.uiuc.groupmessage.GroupMessageProtos.Member getTarget() {
			return target_;
		}
		public edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder getTargetOrBuilder() {
			return target_;
		}

		// required .GroupMessage.Action action = 2 [default = TARGET_HEARTBEATS];
		public static final int ACTION_FIELD_NUMBER = 2;
		private edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.Action action_;
		public boolean hasAction() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}
		public edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.Action getAction() {
			return action_;
		}

		// repeated .Member member = 3;
		public static final int MEMBER_FIELD_NUMBER = 3;
		private java.util.List<edu.uiuc.groupmessage.GroupMessageProtos.Member> member_;
		public java.util.List<edu.uiuc.groupmessage.GroupMessageProtos.Member> getMemberList() {
			return member_;
		}
		public java.util.List<? extends edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder> 
		getMemberOrBuilderList() {
			return member_;
		}
		public int getMemberCount() {
			return member_.size();
		}
		public edu.uiuc.groupmessage.GroupMessageProtos.Member getMember(int index) {
			return member_.get(index);
		}
		public edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder getMemberOrBuilder(
				int index) {
			return member_.get(index);
		}

		// optional bytes file_content = 4;
		public static final int FILE_CONTENT_FIELD_NUMBER = 4;
		private com.google.protobuf.ByteString fileContent_;
		public boolean hasFileContent() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}
		public com.google.protobuf.ByteString getFileContent() {
			return fileContent_;
		}

		// optional string file_name = 5;
		public static final int FILE_NAME_FIELD_NUMBER = 5;
		private java.lang.Object fileName_;
		public boolean hasFileName() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}
		public String getFileName() {
			java.lang.Object ref = fileName_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					fileName_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getFileNameBytes() {
			java.lang.Object ref = fileName_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				fileName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			target_ = edu.uiuc.groupmessage.GroupMessageProtos.Member.getDefaultInstance();
			action_ = edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.Action.TARGET_HEARTBEATS;
			member_ = java.util.Collections.emptyList();
			fileContent_ = com.google.protobuf.ByteString.EMPTY;
			fileName_ = "";
		}
		private byte memoizedIsInitialized = -1;
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) return isInitialized == 1;

			if (!hasTarget()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasAction()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!getTarget().isInitialized()) {
				memoizedIsInitialized = 0;
				return false;
			}
			for (int i = 0; i < getMemberCount(); i++) {
				if (!getMember(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeMessage(1, target_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeEnum(2, action_.getNumber());
			}
			for (int i = 0; i < member_.size(); i++) {
				output.writeMessage(3, member_.get(i));
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeBytes(4, fileContent_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeBytes(5, getFileNameBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, target_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream
						.computeEnumSize(2, action_.getNumber());
			}
			for (int i = 0; i < member_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(3, member_.get(i));
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(4, fileContent_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(5, getFileNameBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;
		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage parseFrom(
				com.google.protobuf.ByteString data)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage parseFrom(
				com.google.protobuf.CodedInputStream input)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() { return Builder.create(); }
		public Builder newBuilderForType() { return newBuilder(); }
		public static Builder newBuilder(edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage prototype) {
			return newBuilder().mergeFrom(prototype);
		}
		public Builder toBuilder() { return newBuilder(this); }

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}
		public static final class Builder extends
		com.google.protobuf.GeneratedMessage.Builder<Builder>
		implements edu.uiuc.groupmessage.GroupMessageProtos.GroupMessageOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return edu.uiuc.groupmessage.GroupMessageProtos.internal_static_GroupMessage_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
			internalGetFieldAccessorTable() {
				return edu.uiuc.groupmessage.GroupMessageProtos.internal_static_GroupMessage_fieldAccessorTable;
			}

			// Construct using edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}
			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getTargetFieldBuilder();
					getMemberFieldBuilder();
				}
			}
			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				if (targetBuilder_ == null) {
					target_ = edu.uiuc.groupmessage.GroupMessageProtos.Member.getDefaultInstance();
				} else {
					targetBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000001);
				action_ = edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.Action.TARGET_HEARTBEATS;
				bitField0_ = (bitField0_ & ~0x00000002);
				if (memberBuilder_ == null) {
					member_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000004);
				} else {
					memberBuilder_.clear();
				}
				fileContent_ = com.google.protobuf.ByteString.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000008);
				fileName_ = "";
				bitField0_ = (bitField0_ & ~0x00000010);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.getDescriptor();
			}

			public edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage getDefaultInstanceForType() {
				return edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.getDefaultInstance();
			}

			public edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage build() {
				edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(
							result).asInvalidProtocolBufferException();
				}
				return result;
			}

			public edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage buildPartial() {
				edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage result = new edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				if (targetBuilder_ == null) {
					result.target_ = target_;
				} else {
					result.target_ = targetBuilder_.build();
				}
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.action_ = action_;
				if (memberBuilder_ == null) {
					if (((bitField0_ & 0x00000004) == 0x00000004)) {
						member_ = java.util.Collections.unmodifiableList(member_);
						bitField0_ = (bitField0_ & ~0x00000004);
					}
					result.member_ = member_;
				} else {
					result.member_ = memberBuilder_.build();
				}
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000004;
				}
				result.fileContent_ = fileContent_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000008;
				}
				result.fileName_ = fileName_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage) {
					return mergeFrom((edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage)other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage other) {
				if (other == edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.getDefaultInstance()) return this;
				if (other.hasTarget()) {
					mergeTarget(other.getTarget());
				}
				if (other.hasAction()) {
					setAction(other.getAction());
				}
				if (memberBuilder_ == null) {
					if (!other.member_.isEmpty()) {
						if (member_.isEmpty()) {
							member_ = other.member_;
							bitField0_ = (bitField0_ & ~0x00000004);
						} else {
							ensureMemberIsMutable();
							member_.addAll(other.member_);
						}
						onChanged();
					}
				} else {
					if (!other.member_.isEmpty()) {
						if (memberBuilder_.isEmpty()) {
							memberBuilder_.dispose();
							memberBuilder_ = null;
							member_ = other.member_;
							bitField0_ = (bitField0_ & ~0x00000004);
							memberBuilder_ = 
									com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
											getMemberFieldBuilder() : null;
						} else {
							memberBuilder_.addAllMessages(other.member_);
						}
					}
				}
				if (other.hasFileContent()) {
					setFileContent(other.getFileContent());
				}
				if (other.hasFileName()) {
					setFileName(other.getFileName());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasTarget()) {

					return false;
				}
				if (!hasAction()) {

					return false;
				}
				if (!getTarget().isInitialized()) {

					return false;
				}
				for (int i = 0; i < getMemberCount(); i++) {
					if (!getMember(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields =
						com.google.protobuf.UnknownFieldSet.newBuilder(
								this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder subBuilder = edu.uiuc.groupmessage.GroupMessageProtos.Member.newBuilder();
						if (hasTarget()) {
							subBuilder.mergeFrom(getTarget());
						}
						input.readMessage(subBuilder, extensionRegistry);
						setTarget(subBuilder.buildPartial());
						break;
					}
					case 16: {
						int rawValue = input.readEnum();
						edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.Action value = edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.Action.valueOf(rawValue);
						if (value == null) {
							unknownFields.mergeVarintField(2, rawValue);
						} else {
							bitField0_ |= 0x00000002;
							action_ = value;
						}
						break;
					}
					case 26: {
						edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder subBuilder = edu.uiuc.groupmessage.GroupMessageProtos.Member.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addMember(subBuilder.buildPartial());
						break;
					}
					case 34: {
						bitField0_ |= 0x00000008;
						fileContent_ = input.readBytes();
						break;
					}
					case 42: {
						bitField0_ |= 0x00000010;
						fileName_ = input.readBytes();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required .Member target = 1;
			private edu.uiuc.groupmessage.GroupMessageProtos.Member target_ = edu.uiuc.groupmessage.GroupMessageProtos.Member.getDefaultInstance();
			private com.google.protobuf.SingleFieldBuilder<
			edu.uiuc.groupmessage.GroupMessageProtos.Member, edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder, edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder> targetBuilder_;
			public boolean hasTarget() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}
			public edu.uiuc.groupmessage.GroupMessageProtos.Member getTarget() {
				if (targetBuilder_ == null) {
					return target_;
				} else {
					return targetBuilder_.getMessage();
				}
			}
			public Builder setTarget(edu.uiuc.groupmessage.GroupMessageProtos.Member value) {
				if (targetBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					target_ = value;
					onChanged();
				} else {
					targetBuilder_.setMessage(value);
				}
				bitField0_ |= 0x00000001;
				return this;
			}
			public Builder setTarget(
					edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder builderForValue) {
				if (targetBuilder_ == null) {
					target_ = builderForValue.build();
					onChanged();
				} else {
					targetBuilder_.setMessage(builderForValue.build());
				}
				bitField0_ |= 0x00000001;
				return this;
			}
			public Builder mergeTarget(edu.uiuc.groupmessage.GroupMessageProtos.Member value) {
				if (targetBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001) &&
							target_ != edu.uiuc.groupmessage.GroupMessageProtos.Member.getDefaultInstance()) {
						target_ =
								edu.uiuc.groupmessage.GroupMessageProtos.Member.newBuilder(target_).mergeFrom(value).buildPartial();
					} else {
						target_ = value;
					}
					onChanged();
				} else {
					targetBuilder_.mergeFrom(value);
				}
				bitField0_ |= 0x00000001;
				return this;
			}
			public Builder clearTarget() {
				if (targetBuilder_ == null) {
					target_ = edu.uiuc.groupmessage.GroupMessageProtos.Member.getDefaultInstance();
					onChanged();
				} else {
					targetBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000001);
				return this;
			}
			public edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder getTargetBuilder() {
				bitField0_ |= 0x00000001;
				onChanged();
				return getTargetFieldBuilder().getBuilder();
			}
			public edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder getTargetOrBuilder() {
				if (targetBuilder_ != null) {
					return targetBuilder_.getMessageOrBuilder();
				} else {
					return target_;
				}
			}
			private com.google.protobuf.SingleFieldBuilder<
			edu.uiuc.groupmessage.GroupMessageProtos.Member, edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder, edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder> 
			getTargetFieldBuilder() {
				if (targetBuilder_ == null) {
					targetBuilder_ = new com.google.protobuf.SingleFieldBuilder<
							edu.uiuc.groupmessage.GroupMessageProtos.Member, edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder, edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder>(
									target_,
									getParentForChildren(),
									isClean());
					target_ = null;
				}
				return targetBuilder_;
			}

			// required .GroupMessage.Action action = 2 [default = TARGET_HEARTBEATS];
			private edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.Action action_ = edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.Action.TARGET_HEARTBEATS;
			public boolean hasAction() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}
			public edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.Action getAction() {
				return action_;
			}
			public Builder setAction(edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.Action value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				action_ = value;
				onChanged();
				return this;
			}
			public Builder clearAction() {
				bitField0_ = (bitField0_ & ~0x00000002);
				action_ = edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.Action.TARGET_HEARTBEATS;
				onChanged();
				return this;
			}

			// repeated .Member member = 3;
			private java.util.List<edu.uiuc.groupmessage.GroupMessageProtos.Member> member_ =
					java.util.Collections.emptyList();
			private void ensureMemberIsMutable() {
				if (!((bitField0_ & 0x00000004) == 0x00000004)) {
					member_ = new java.util.ArrayList<edu.uiuc.groupmessage.GroupMessageProtos.Member>(member_);
					bitField0_ |= 0x00000004;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<
			edu.uiuc.groupmessage.GroupMessageProtos.Member, edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder, edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder> memberBuilder_;

			public java.util.List<edu.uiuc.groupmessage.GroupMessageProtos.Member> getMemberList() {
				if (memberBuilder_ == null) {
					return java.util.Collections.unmodifiableList(member_);
				} else {
					return memberBuilder_.getMessageList();
				}
			}
			public int getMemberCount() {
				if (memberBuilder_ == null) {
					return member_.size();
				} else {
					return memberBuilder_.getCount();
				}
			}
			public edu.uiuc.groupmessage.GroupMessageProtos.Member getMember(int index) {
				if (memberBuilder_ == null) {
					return member_.get(index);
				} else {
					return memberBuilder_.getMessage(index);
				}
			}
			public Builder setMember(
					int index, edu.uiuc.groupmessage.GroupMessageProtos.Member value) {
				if (memberBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureMemberIsMutable();
					member_.set(index, value);
					onChanged();
				} else {
					memberBuilder_.setMessage(index, value);
				}
				return this;
			}
			public Builder setMember(
					int index, edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder builderForValue) {
				if (memberBuilder_ == null) {
					ensureMemberIsMutable();
					member_.set(index, builderForValue.build());
					onChanged();
				} else {
					memberBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}
			public Builder addMember(edu.uiuc.groupmessage.GroupMessageProtos.Member value) {
				if (memberBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureMemberIsMutable();
					member_.add(value);
					onChanged();
				} else {
					memberBuilder_.addMessage(value);
				}
				return this;
			}
			public Builder addMember(
					int index, edu.uiuc.groupmessage.GroupMessageProtos.Member value) {
				if (memberBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureMemberIsMutable();
					member_.add(index, value);
					onChanged();
				} else {
					memberBuilder_.addMessage(index, value);
				}
				return this;
			}
			public Builder addMember(
					edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder builderForValue) {
				if (memberBuilder_ == null) {
					ensureMemberIsMutable();
					member_.add(builderForValue.build());
					onChanged();
				} else {
					memberBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}
			public Builder addMember(
					int index, edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder builderForValue) {
				if (memberBuilder_ == null) {
					ensureMemberIsMutable();
					member_.add(index, builderForValue.build());
					onChanged();
				} else {
					memberBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}
			public Builder addAllMember(
					java.lang.Iterable<? extends edu.uiuc.groupmessage.GroupMessageProtos.Member> values) {
				if (memberBuilder_ == null) {
					ensureMemberIsMutable();
					super.addAll(values, member_);
					onChanged();
				} else {
					memberBuilder_.addAllMessages(values);
				}
				return this;
			}
			public Builder clearMember() {
				if (memberBuilder_ == null) {
					member_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000004);
					onChanged();
				} else {
					memberBuilder_.clear();
				}
				return this;
			}
			public Builder removeMember(int index) {
				if (memberBuilder_ == null) {
					ensureMemberIsMutable();
					member_.remove(index);
					onChanged();
				} else {
					memberBuilder_.remove(index);
				}
				return this;
			}
			public edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder getMemberBuilder(
					int index) {
				return getMemberFieldBuilder().getBuilder(index);
			}
			public edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder getMemberOrBuilder(
					int index) {
				if (memberBuilder_ == null) {
					return member_.get(index);  } else {
						return memberBuilder_.getMessageOrBuilder(index);
					}
			}
			public java.util.List<? extends edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder> 
			getMemberOrBuilderList() {
				if (memberBuilder_ != null) {
					return memberBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(member_);
				}
			}
			public edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder addMemberBuilder() {
				return getMemberFieldBuilder().addBuilder(
						edu.uiuc.groupmessage.GroupMessageProtos.Member.getDefaultInstance());
			}
			public edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder addMemberBuilder(
					int index) {
				return getMemberFieldBuilder().addBuilder(
						index, edu.uiuc.groupmessage.GroupMessageProtos.Member.getDefaultInstance());
			}
			public java.util.List<edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder> 
			getMemberBuilderList() {
				return getMemberFieldBuilder().getBuilderList();
			}
			private com.google.protobuf.RepeatedFieldBuilder<
			edu.uiuc.groupmessage.GroupMessageProtos.Member, edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder, edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder> 
			getMemberFieldBuilder() {
				if (memberBuilder_ == null) {
					memberBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
							edu.uiuc.groupmessage.GroupMessageProtos.Member, edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder, edu.uiuc.groupmessage.GroupMessageProtos.MemberOrBuilder>(
									member_,
									((bitField0_ & 0x00000004) == 0x00000004),
									getParentForChildren(),
									isClean());
					member_ = null;
				}
				return memberBuilder_;
			}

			// optional bytes file_content = 4;
			private com.google.protobuf.ByteString fileContent_ = com.google.protobuf.ByteString.EMPTY;
			public boolean hasFileContent() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}
			public com.google.protobuf.ByteString getFileContent() {
				return fileContent_;
			}
			public Builder setFileContent(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				fileContent_ = value;
				onChanged();
				return this;
			}
			public Builder clearFileContent() {
				bitField0_ = (bitField0_ & ~0x00000008);
				fileContent_ = getDefaultInstance().getFileContent();
				onChanged();
				return this;
			}

			// optional string file_name = 5;
			private java.lang.Object fileName_ = "";
			public boolean hasFileName() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}
			public String getFileName() {
				java.lang.Object ref = fileName_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					fileName_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setFileName(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000010;
				fileName_ = value;
				onChanged();
				return this;
			}
			public Builder clearFileName() {
				bitField0_ = (bitField0_ & ~0x00000010);
				fileName_ = getDefaultInstance().getFileName();
				onChanged();
				return this;
			}
			void setFileName(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000010;
				fileName_ = value;
				onChanged();
			}

			// @@protoc_insertion_point(builder_scope:GroupMessage)
		}

		static {
			defaultInstance = new GroupMessage(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:GroupMessage)
	}

	private static com.google.protobuf.Descriptors.Descriptor
	internal_static_Member_descriptor;
	private static
	com.google.protobuf.GeneratedMessage.FieldAccessorTable
	internal_static_Member_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor
	internal_static_GroupMessage_descriptor;
	private static
	com.google.protobuf.GeneratedMessage.FieldAccessorTable
	internal_static_GroupMessage_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}
	private static com.google.protobuf.Descriptors.FileDescriptor
	descriptor;
	static {
		java.lang.String[] descriptorData = {
				"\n\023group_message.proto\"5\n\006Member\022\n\n\002ip\030\001 " +
						"\002(\t\022\014\n\004port\030\002 \002(\005\022\021\n\ttimestamp\030\003 \001(\005\"\364\003\n" +
						"\014GroupMessage\022\027\n\006target\030\001 \002(\0132\007.Member\0227" +
						"\n\006action\030\002 \002(\0162\024.GroupMessage.Action:\021TA" +
						"RGET_HEARTBEATS\022\027\n\006member\030\003 \003(\0132\007.Member" +
						"\022\024\n\014file_content\030\004 \001(\014\022\021\n\tfile_name\030\005 \001(" +
						"\t\"\317\002\n\006Action\022\020\n\014JOIN_REQUEST\020\000\022\024\n\020RESET_" +
						"MEMBERLIST\020\001\022\020\n\014TARGET_JOINS\020\002\022\021\n\rTARGET" +
						"_LEAVES\020\003\022\020\n\014TARGET_FAILS\020\004\022\025\n\021TARGET_HE" +
						"ARTBEATS\020\005\022\025\n\021GET_FILE_LOCATION\020\006\022\021\n\rFIL",
						"E_LOCATION\020\007\022\014\n\010PUT_FILE\020\010\022\014\n\010GET_FILE\020\t" +
								"\022\017\n\013DELETE_FILE\020\n\022\022\n\016DELETE_REPLICA\020\013\022\013\n" +
								"\007FILE_OK\020\014\022\016\n\nFILE_ERROR\020\r\022\r\n\tPUSH_FILE\020" +
								"\016\022\022\n\016FILE_NOT_EXIST\020\017\022\016\n\nFILE_EXIST\020\020\022\024\n" +
								"\020CHECK_FILE_EXIST\020\021B+\n\025edu.uiuc.groupmes" +
								"sageB\022GroupMessageProtos"
		};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
				new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_Member_descriptor =
						getDescriptor().getMessageTypes().get(0);
				internal_static_Member_fieldAccessorTable = new
						com.google.protobuf.GeneratedMessage.FieldAccessorTable(
								internal_static_Member_descriptor,
								new java.lang.String[] { "Ip", "Port", "Timestamp", },
								edu.uiuc.groupmessage.GroupMessageProtos.Member.class,
								edu.uiuc.groupmessage.GroupMessageProtos.Member.Builder.class);
				internal_static_GroupMessage_descriptor =
						getDescriptor().getMessageTypes().get(1);
				internal_static_GroupMessage_fieldAccessorTable = new
						com.google.protobuf.GeneratedMessage.FieldAccessorTable(
								internal_static_GroupMessage_descriptor,
								new java.lang.String[] { "Target", "Action", "Member", "FileContent", "FileName", },
								edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.class,
								edu.uiuc.groupmessage.GroupMessageProtos.GroupMessage.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
		.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {
		}, assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
