// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group_message.proto

public final class GroupMessage {
  private GroupMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .Message.Member target = 1;
    boolean hasTarget();
    GroupMessage.Message.Member getTarget();
    GroupMessage.Message.MemberOrBuilder getTargetOrBuilder();
    
    // required .Message.Action action = 2 [default = TARGET_HEARTBEATS];
    boolean hasAction();
    GroupMessage.Message.Action getAction();
  }
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(Builder builder) {
      super(builder);
    }
    private Message(boolean noInit) {}
    
    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }
    
    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GroupMessage.internal_static_Message_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GroupMessage.internal_static_Message_fieldAccessorTable;
    }
    
    public enum Action
        implements com.google.protobuf.ProtocolMessageEnum {
      TARGET_JOINS(0, 0),
      TARGET_LEAVES(1, 1),
      TARGET_FAILS(2, 2),
      TARGET_HEARTBEATS(3, 3),
      ;
      
      public static final int TARGET_JOINS_VALUE = 0;
      public static final int TARGET_LEAVES_VALUE = 1;
      public static final int TARGET_FAILS_VALUE = 2;
      public static final int TARGET_HEARTBEATS_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static Action valueOf(int value) {
        switch (value) {
          case 0: return TARGET_JOINS;
          case 1: return TARGET_LEAVES;
          case 2: return TARGET_FAILS;
          case 3: return TARGET_HEARTBEATS;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Action>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Action>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Action>() {
              public Action findValueByNumber(int number) {
                return Action.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return GroupMessage.Message.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Action[] VALUES = {
        TARGET_JOINS, TARGET_LEAVES, TARGET_FAILS, TARGET_HEARTBEATS, 
      };
      
      public static Action valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Action(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:Message.Action)
    }
    
    public interface MemberOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string ip = 1;
      boolean hasIp();
      String getIp();
      
      // required int32 port = 2;
      boolean hasPort();
      int getPort();
      
      // required int32 timestamp = 3;
      boolean hasTimestamp();
      int getTimestamp();
    }
    public static final class Member extends
        com.google.protobuf.GeneratedMessage
        implements MemberOrBuilder {
      // Use Member.newBuilder() to construct.
      private Member(Builder builder) {
        super(builder);
      }
      private Member(boolean noInit) {}
      
      private static final Member defaultInstance;
      public static Member getDefaultInstance() {
        return defaultInstance;
      }
      
      public Member getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GroupMessage.internal_static_Message_Member_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GroupMessage.internal_static_Message_Member_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string ip = 1;
      public static final int IP_FIELD_NUMBER = 1;
      private java.lang.Object ip_;
      public boolean hasIp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getIp() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            ip_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required int32 port = 2;
      public static final int PORT_FIELD_NUMBER = 2;
      private int port_;
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getPort() {
        return port_;
      }
      
      // required int32 timestamp = 3;
      public static final int TIMESTAMP_FIELD_NUMBER = 3;
      private int timestamp_;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getTimestamp() {
        return timestamp_;
      }
      
      private void initFields() {
        ip_ = "";
        port_ = 0;
        timestamp_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasIp()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPort()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTimestamp()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getIpBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, port_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, timestamp_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getIpBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, port_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, timestamp_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static GroupMessage.Message.Member parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static GroupMessage.Message.Member parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static GroupMessage.Message.Member parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static GroupMessage.Message.Member parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static GroupMessage.Message.Member parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static GroupMessage.Message.Member parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static GroupMessage.Message.Member parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static GroupMessage.Message.Member parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static GroupMessage.Message.Member parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static GroupMessage.Message.Member parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(GroupMessage.Message.Member prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements GroupMessage.Message.MemberOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return GroupMessage.internal_static_Message_Member_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return GroupMessage.internal_static_Message_Member_fieldAccessorTable;
        }
        
        // Construct using GroupMessage.Message.Member.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          ip_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          port_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          timestamp_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return GroupMessage.Message.Member.getDescriptor();
        }
        
        public GroupMessage.Message.Member getDefaultInstanceForType() {
          return GroupMessage.Message.Member.getDefaultInstance();
        }
        
        public GroupMessage.Message.Member build() {
          GroupMessage.Message.Member result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private GroupMessage.Message.Member buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          GroupMessage.Message.Member result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public GroupMessage.Message.Member buildPartial() {
          GroupMessage.Message.Member result = new GroupMessage.Message.Member(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.ip_ = ip_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.port_ = port_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.timestamp_ = timestamp_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof GroupMessage.Message.Member) {
            return mergeFrom((GroupMessage.Message.Member)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(GroupMessage.Message.Member other) {
          if (other == GroupMessage.Message.Member.getDefaultInstance()) return this;
          if (other.hasIp()) {
            setIp(other.getIp());
          }
          if (other.hasPort()) {
            setPort(other.getPort());
          }
          if (other.hasTimestamp()) {
            setTimestamp(other.getTimestamp());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasIp()) {
            
            return false;
          }
          if (!hasPort()) {
            
            return false;
          }
          if (!hasTimestamp()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                ip_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                port_ = input.readInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                timestamp_ = input.readInt32();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string ip = 1;
        private java.lang.Object ip_ = "";
        public boolean hasIp() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getIp() {
          java.lang.Object ref = ip_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            ip_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setIp(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          ip_ = value;
          onChanged();
          return this;
        }
        public Builder clearIp() {
          bitField0_ = (bitField0_ & ~0x00000001);
          ip_ = getDefaultInstance().getIp();
          onChanged();
          return this;
        }
        void setIp(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          ip_ = value;
          onChanged();
        }
        
        // required int32 port = 2;
        private int port_ ;
        public boolean hasPort() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public int getPort() {
          return port_;
        }
        public Builder setPort(int value) {
          bitField0_ |= 0x00000002;
          port_ = value;
          onChanged();
          return this;
        }
        public Builder clearPort() {
          bitField0_ = (bitField0_ & ~0x00000002);
          port_ = 0;
          onChanged();
          return this;
        }
        
        // required int32 timestamp = 3;
        private int timestamp_ ;
        public boolean hasTimestamp() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public int getTimestamp() {
          return timestamp_;
        }
        public Builder setTimestamp(int value) {
          bitField0_ |= 0x00000004;
          timestamp_ = value;
          onChanged();
          return this;
        }
        public Builder clearTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000004);
          timestamp_ = 0;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:Message.Member)
      }
      
      static {
        defaultInstance = new Member(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:Message.Member)
    }
    
    private int bitField0_;
    // required .Message.Member target = 1;
    public static final int TARGET_FIELD_NUMBER = 1;
    private GroupMessage.Message.Member target_;
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public GroupMessage.Message.Member getTarget() {
      return target_;
    }
    public GroupMessage.Message.MemberOrBuilder getTargetOrBuilder() {
      return target_;
    }
    
    // required .Message.Action action = 2 [default = TARGET_HEARTBEATS];
    public static final int ACTION_FIELD_NUMBER = 2;
    private GroupMessage.Message.Action action_;
    public boolean hasAction() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public GroupMessage.Message.Action getAction() {
      return action_;
    }
    
    private void initFields() {
      target_ = GroupMessage.Message.Member.getDefaultInstance();
      action_ = GroupMessage.Message.Action.TARGET_HEARTBEATS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTarget()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTarget().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, target_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, action_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, target_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, action_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static GroupMessage.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static GroupMessage.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static GroupMessage.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static GroupMessage.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static GroupMessage.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static GroupMessage.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static GroupMessage.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static GroupMessage.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static GroupMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static GroupMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(GroupMessage.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements GroupMessage.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GroupMessage.internal_static_Message_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GroupMessage.internal_static_Message_fieldAccessorTable;
      }
      
      // Construct using GroupMessage.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTargetFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (targetBuilder_ == null) {
          target_ = GroupMessage.Message.Member.getDefaultInstance();
        } else {
          targetBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = GroupMessage.Message.Action.TARGET_HEARTBEATS;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GroupMessage.Message.getDescriptor();
      }
      
      public GroupMessage.Message getDefaultInstanceForType() {
        return GroupMessage.Message.getDefaultInstance();
      }
      
      public GroupMessage.Message build() {
        GroupMessage.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private GroupMessage.Message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        GroupMessage.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public GroupMessage.Message buildPartial() {
        GroupMessage.Message result = new GroupMessage.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (targetBuilder_ == null) {
          result.target_ = target_;
        } else {
          result.target_ = targetBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.action_ = action_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GroupMessage.Message) {
          return mergeFrom((GroupMessage.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(GroupMessage.Message other) {
        if (other == GroupMessage.Message.getDefaultInstance()) return this;
        if (other.hasTarget()) {
          mergeTarget(other.getTarget());
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTarget()) {
          
          return false;
        }
        if (!hasAction()) {
          
          return false;
        }
        if (!getTarget().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              GroupMessage.Message.Member.Builder subBuilder = GroupMessage.Message.Member.newBuilder();
              if (hasTarget()) {
                subBuilder.mergeFrom(getTarget());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTarget(subBuilder.buildPartial());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              GroupMessage.Message.Action value = GroupMessage.Message.Action.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                action_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .Message.Member target = 1;
      private GroupMessage.Message.Member target_ = GroupMessage.Message.Member.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          GroupMessage.Message.Member, GroupMessage.Message.Member.Builder, GroupMessage.Message.MemberOrBuilder> targetBuilder_;
      public boolean hasTarget() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public GroupMessage.Message.Member getTarget() {
        if (targetBuilder_ == null) {
          return target_;
        } else {
          return targetBuilder_.getMessage();
        }
      }
      public Builder setTarget(GroupMessage.Message.Member value) {
        if (targetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          target_ = value;
          onChanged();
        } else {
          targetBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setTarget(
          GroupMessage.Message.Member.Builder builderForValue) {
        if (targetBuilder_ == null) {
          target_ = builderForValue.build();
          onChanged();
        } else {
          targetBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeTarget(GroupMessage.Message.Member value) {
        if (targetBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              target_ != GroupMessage.Message.Member.getDefaultInstance()) {
            target_ =
              GroupMessage.Message.Member.newBuilder(target_).mergeFrom(value).buildPartial();
          } else {
            target_ = value;
          }
          onChanged();
        } else {
          targetBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearTarget() {
        if (targetBuilder_ == null) {
          target_ = GroupMessage.Message.Member.getDefaultInstance();
          onChanged();
        } else {
          targetBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public GroupMessage.Message.Member.Builder getTargetBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTargetFieldBuilder().getBuilder();
      }
      public GroupMessage.Message.MemberOrBuilder getTargetOrBuilder() {
        if (targetBuilder_ != null) {
          return targetBuilder_.getMessageOrBuilder();
        } else {
          return target_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          GroupMessage.Message.Member, GroupMessage.Message.Member.Builder, GroupMessage.Message.MemberOrBuilder> 
          getTargetFieldBuilder() {
        if (targetBuilder_ == null) {
          targetBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              GroupMessage.Message.Member, GroupMessage.Message.Member.Builder, GroupMessage.Message.MemberOrBuilder>(
                  target_,
                  getParentForChildren(),
                  isClean());
          target_ = null;
        }
        return targetBuilder_;
      }
      
      // required .Message.Action action = 2 [default = TARGET_HEARTBEATS];
      private GroupMessage.Message.Action action_ = GroupMessage.Message.Action.TARGET_HEARTBEATS;
      public boolean hasAction() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public GroupMessage.Message.Action getAction() {
        return action_;
      }
      public Builder setAction(GroupMessage.Message.Action value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        action_ = value;
        onChanged();
        return this;
      }
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        action_ = GroupMessage.Message.Action.TARGET_HEARTBEATS;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Message)
    }
    
    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Message)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_Member_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Message_Member_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023group_message.proto\"\355\001\n\007Message\022\037\n\006tar" +
      "get\030\001 \002(\0132\017.Message.Member\0222\n\006action\030\002 \002" +
      "(\0162\017.Message.Action:\021TARGET_HEARTBEATS\0325" +
      "\n\006Member\022\n\n\002ip\030\001 \002(\t\022\014\n\004port\030\002 \002(\005\022\021\n\tti" +
      "mestamp\030\003 \002(\005\"V\n\006Action\022\020\n\014TARGET_JOINS\020" +
      "\000\022\021\n\rTARGET_LEAVES\020\001\022\020\n\014TARGET_FAILS\020\002\022\025" +
      "\n\021TARGET_HEARTBEATS\020\003B\016B\014GroupMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Message_descriptor,
              new java.lang.String[] { "Target", "Action", },
              GroupMessage.Message.class,
              GroupMessage.Message.Builder.class);
          internal_static_Message_Member_descriptor =
            internal_static_Message_descriptor.getNestedTypes().get(0);
          internal_static_Message_Member_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Message_Member_descriptor,
              new java.lang.String[] { "Ip", "Port", "Timestamp", },
              GroupMessage.Message.Member.class,
              GroupMessage.Message.Member.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
